#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
users:
  - name: dave
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDRtF8BNePp7GXToVkBg7KupvHZnNamCbXw6flHovYF8XOWcqy55wJJdOh7EhZrsXXrjnwkD01IBJuulz0Dnu/RhsiKqbUlkr6tfDYHtY6GtebCCru42mvf/5296BaqH62XOhBJ687tGXAvSKU6jGnp27RGaTGALQFguk0JQSMcW3KEwQvoAeozPzZQE7Z2ubtUH0dNLgDpnat4nBj8m0GvjQ9AF5oa8eHYX8nLTxKKBzCdiOUGt/MSLYIFG1FaaZCckQXSyy505l0AHTXQe83I+dKGb3lSLxCjPRdtZP19FuOjju8c5yrwaWfnFzOHLtL7IAe6aUe6pcTfaUD/DqTZUVaIOxZZayhihFU0FOtH6HMsJcJub4FK+wQKE83uceI8NlrUmxRLUPTnuG1s+s/7QWMJfnUoG0oNpjVM6Ij0XBpgl3imNLc+5E4CnRVbXfVbhQY+9CW2fqm0q++T0XWmhkWUGkBstWFqIPeAQywCNTO5JfzW6FmPvUhGUkznpws= dave@HP-850
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    