#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${domain}
users:
  - name: user
    shell: /bin/bash
    ssh-authorized-keys:
      - "public key"
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    
